[package]
name = "chat-server"
version = "0.1.0"
authors = ["Karsten Jeschkies <k@jeschkies.xyz>"]
edition = "2018"

[dependencies]
pretty_env_logger = "0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
